In [15]:
import pandas as pd
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')

def OLS_model_predict(region, pred_year_month):
    pred_year = int(str(pred_year_month).split("-")[0])
    month = int(str(pred_year_month).split("-")[-1])

    df_weather = pd.read_csv('static/data/기상데이터 0510 index X.csv')
    df_tmp_region = df_weather[df_weather['조사지역'] == region]
    df_weather_region = df_tmp_region.groupby(['조사지역', '관측일자']).mean()
    df_weather_region = df_weather_region.reset_index(drop=False)

    df_group_mean = df_weather_region.groupby(['연', '월']).mean()
    df_group_mean = df_group_mean.reset_index(drop=False)
    df_month_mean = df_group_mean[df_group_mean['월'] == month]

    for i in df_month_mean.index:
        df_tmp = df_weather_region.loc[(df_weather_region['연'] == df_month_mean.loc[i, '연']) & (df_weather_region['월'] == df_month_mean.loc[i, '월'])]
        temp_max = df_tmp['temp_max'].max()
        temp_min = df_tmp['temp_min'].min()
        df_month_mean.loc[i, 'temp_max'] = temp_max
        df_month_mean.loc[i, 'temp_min'] = temp_min

    pred_list = []
    for value in df_month_mean.columns[2: -3]:
        df_target = df_month_mean[value]
        X_train2 = pd.DataFrame(df_month_mean[['연']], columns = ['연'])
        y_train2 = df_target.values

        # import statsmodels.api as sm
        X_train = sm.add_constant(X_train2)
        model = sm.OLS(y_train2, X_train2).fit()
        pred_value = model.predict(pred_year)

        pred_list.append(float(pred_value))
    
    # print(f'\t\t\t{region}의 {month}월 {pred_year}의 예측값:')
    # print(pred_list)
    return pred_list

In [4]:
OLS_model_predict("속초", '2023-3')

/var/folders/rt/5jvyxhl160n0wkcqnqvygf8m0000gn/T/ipykernel_75389/772096590.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_month_mean.loc[i, 'temp_max'] = temp_max
/var/folders/rt/5jvyxhl160n0wkcqnqvygf8m0000gn/T/ipykernel_75389/772096590.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_month_mean.loc[i, 'temp_min'] = temp_min

[6.336571669852754, 19.640154537406413, -4.372147188384846]

In [5]:
df = pd.read_csv('static/data/기상데이터 0510 index X.csv')
region = sorted(df['조사지역'].unique())
region.remove('고산')
region.remove('관악산')
region.remove('대관령')
region.remove('흑산도')
region.remove('문산')
region.remove('추풍령')
len(region)

67

In [ ]:
import numpy as np

for i in range(2081,2090):
    reg_pred_list = []
    for j in range(1,13):
        cnt = 0
        for reg in region:
            pred = OLS_model_predict(reg, f"{i}-{j}")
            reg_pred_list.append(cnt)
            reg_pred_list.append(j)
            reg_pred_list.append(reg)
            for k in pred:
                reg_pred_list.append(k)
    reg_pred_array = np.array(reg_pred_list)
    reg_pred_array = reg_pred_array.reshape(-1,6)
    df2 = pd.DataFrame(reg_pred_array, columns=['KOR_NUM', 'month', 'KOR_NM','temperature', 'temp_max', 'temp_min'])
    df2.to_csv(f"{i}예측.csv", mode='w')

In [22]:
import numpy as np
reg_pred_array = np.array(reg_pred_list)    
reg_pred_array = reg_pred_array.reshape(-1,6)

df3.head(67)

,KOR_NUM,month,KOR_NM,temperature,temp_max,temp_min
0,0,1,강화,-3.2989771952048534,9.01830763484409,-15.65790774840127
1,1,1,거제,2.778915906947648,13.959736721181768,-7.168604069331287
2,2,1,거창,-1.3381582079292973,12.530716126985189,-14.376271134860028
3,3,1,고창,-0.18208859470118965,12.26068957477404,-10.740687252606289
4,4,1,고흥,1.6969662543252548,14.056074955556667,-9.688800330366254
...,...,...,...,...,...,...
62,62,1,통영,3.2972343293569173,14.165645683759319,-7.15889008481573
63,63,1,포항,2.3537051036730445,13.781381280456353,-8.754197588427289
64,64,1,합천,-0.1432074518805744,13.430604093566483,-12.879925587994043
65,65,1,해남,1.3978682840441836,14.132396584201734,-10.288431816066652
66,66,1,홍천,-4.909267697424229,9.006103036759075,-19.79852026991756

In [8]:

reg_pred_list = []
cnt = 0

for j in range(1,13):
    for reg in region:
        pred = OLS_model_predict(reg, f"2081-{j}")
        reg_pred_list.append(cnt)
        reg_pred_list.append(j)
        reg_pred_list.append(reg)
        reg_pred_list.append(pred)
        cnt++
    df2 = pd.DataFrame(reg_pred_list,columns=['KOR_NUM', 'month', 'KOR_NM','temperature', 'temp_max', 'temp_min'])

df2

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 11)

In [17]:
reg_pred_list = []
cnt = 0
for reg in region:
    pred = OLS_model_predict(reg, f"2081-1")
    reg_pred_list.append(cnt)
    reg_pred_list.append(1)
    reg_pred_list.append(reg)
    for i in pred:
        reg_pred_list.append(i)
        print(i)
    cnt += 1
reg_pred_list

-3.2989771952048534
9.01830763484409
-15.65790774840127
2.778915906947648
13.959736721181768
-7.168604069331287
-1.3381582079292973
12.530716126985189
-14.376271134860028
-0.18208859470118965
12.26068957477404
-10.740687252606289
1.6969662543252548
14.056074955556667
-9.688800330366254
1.1311802384366292
13.395673386153511
-9.246333364237357
-0.6131879046463565
11.799361650586095
-12.058911981067837
-0.06320621808221094
11.458978782084676
-10.706189351729439
-2.3874105321891212
11.972373512435945
-16.22588596117202
-1.4521399764198097
12.829097252755593
-14.944730018301842
2.313312039873344
13.55427252280481
-8.259517955527278
1.057024707897673
12.89611309720884
-9.682115310571747
-1.0215085589424566
11.761582414827055
-13.299406143139263
-3.8802370576836758
10.17769159300414
-17.264834158187504
1.2015974395332893
12.573732896286627
-9.837170985377771
1.9373436616899913
12.891445415246123
-7.323196631065922
-1.6869700387118487
10.399318842414681
-13.832978688768506
0.519143854076558
14.115145683563876
-11.858213488564633
-0.27837356673628577
11.683005331494684
-11.784678270825065
-2.9944310088765285
10.880975997595531
-16.900923582762438
-4.072724413998167
9.986861995013735
-19.276276762258654
3.740038673021574
14.915744837343272
-7.5591867037320695
-0.15261711750688248
12.504406432931102
-12.5250604819201
-1.5383136670726159
11.601666980030378
-14.734276129656037
0.43894873693813874
13.136114181751688
-11.429055923570862
-0.98326887591438
11.210314338266992
-12.455644527393455
7.508128253274109
17.303820260262572
-1.1614423240147107
-1.7286337618730212
10.634283977311453
-13.575812484815247
-2.003799207715337
9.682461393454915
-13.401689903968567
0.1093900730466886
10.832419385897868
-11.443725992451771
-2.1396011892667635
10.397653503412776
-14.277661176944342
-1.8549455926418856
11.119885589968394
-15.20971414584664
-3.5778014523481065
9.642858567119186
-17.504026250201267
2.925779922800321
12.888284820710538
-7.005025184527754
1.1157852851280612
13.097806947747817
-10.551173799804266
-3.677891663940131
10.0200846808731
-18.17125179705168
-2.3667721706823426
9.985590066468761
-15.860676822256757
-0.510462559969546
12.576291101535565
-13.246878452205266
2.933186373440917
13.82696660791349
-5.72441202976921
1.8129964558313414
11.666226227607808
-6.759616924682089
2.4699476839178245
14.584661837086955
-8.534701175218737
1.4491927599044678
13.386299568574401
-10.06679235115849
-3.239810140976915
9.859255024246039
-16.651150833223504
-3.077334088945153
11.898940344777312
-17.943458335662392
-3.152002407907165
9.910000536230397
-17.200141814993838
-4.732987813557666
8.35455172365024
-19.29183718112104
-1.6066935010848153
9.748557308193075
-12.374668242357236
-2.5940686696762616
12.176470716330252
-17.040789874122318
-3.145234782276425
11.193960637846233
-17.855363973042934
0.9998119171497618
14.126403730173559
-10.547939255934667
0.028331884597936362
12.928789828921184
-11.62336667260228
-0.19314548734584697
12.841674555484017
-11.837898127525397
6.370047516111924
16.558254200853433
-0.8887364070125862
-4.850139802606061
8.889155122995584
-19.91132110502977
-0.6311963006433231
11.873982239785724
-9.35744943451188
0.2894226323008726
13.60207337230889
-12.207147858050968
2.717691615984804
13.893220774226432
-8.110576601897689
-2.4168688333759256
10.909947867673976
-16.215880616280465
-5.823867816532312
7.988827897370267
-20.869806523880616
-1.5284596771568921
10.839284842067359
-13.854644364646765
-4.237062648503526
8.405408159635614
-18.059007128026416
-4.836076381800831
8.498757361929826
-17.888342418038043
3.2972343293569173
14.165645683759319
-7.15889008481573
2.3537051036730445
13.781381280456353
-8.754197588427289
-0.1432074518805744
13.430604093566483
-12.879925587994043
1.3978682840441836
14.132396584201734
-10.288431816066652
-4.909267697424229
9.006103036759075
-19.79852026991756

[0,
 1,
 '강화',
 -3.2989771952048534,
 9.01830763484409,
 -15.65790774840127,
 1,
 1,
 '거제',
 2.778915906947648,
 13.959736721181768,
 -7.168604069331287,
 2,
 1,
 '거창',
 -1.3381582079292973,
 12.530716126985189,
 -14.376271134860028,
 3,
 1,
 '고창',
 -0.18208859470118965,
 12.26068957477404,
 -10.740687252606289,
 4,
 1,
 '고흥',
 1.6969662543252548,
 14.056074955556667,
 -9.688800330366254,
 5,
 1,
 '광주',
 1.1311802384366292,
 13.395673386153511,
 -9.246333364237357,
 6,
 1,
 '구미',
 -0.6131879046463565,
 11.799361650586095,
 -12.058911981067837,
 7,
 1,
 '군산',
 -0.06320621808221094,
 11.458978782084676,
 -10.706189351729439,
 8,
 1,
 '금산',
 -2.3874105321891212,
 11.972373512435945,
 -16.22588596117202,
 9,
 1,
 '남원',
 -1.4521399764198097,
 12.829097252755593,
 -14.944730018301842,
 10,
 1,
 '남해',
 2.313312039873344,
 13.55427252280481,
 -8.259517955527278,
 11,
 1,
 '대구',
 1.057024707897673,
 12.89611309720884,
 -9.682115310571747,
 12,
 1,
 '대전',
 -1.0215085589424566,
 11.761582414827055,
 -13.299406143139263,
 13,
 1,
 '동두천',
 -3.8802370576836758,
 10.17769159300414,
 -17.264834158187504,
 14,
 1,
 '동해',
 1.2015974395332893,
 12.573732896286627,
 -9.837170985377771,
 15,
 1,
 '목포',
 1.9373436616899913,
 12.891445415246123,
 -7.323196631065922,
 16,
 1,
 '문경',
 -1.6869700387118487,
 10.399318842414681,
 -13.832978688768506,
 17,
 1,
 '밀양',
 0.519143854076558,
 14.115145683563876,
 -11.858213488564633,
 18,
 1,
 '보령',
 -0.27837356673628577,
 11.683005331494684,
 -11.784678270825065,
 19,
 1,
 '보은',
 -2.9944310088765285,
 10.880975997595531,
 -16.900923582762438,
 20,
 1,
 '봉화',
 -4.072724413998167,
 9.986861995013735,
 -19.276276762258654,
 21,
 1,
 '부산',
 3.740038673021574,
 14.915744837343272,
 -7.5591867037320695,
 22,
 1,
 '부안',
 -0.15261711750688248,
 12.504406432931102,
 -12.5250604819201,
 23,
 1,
 '부여',
 -1.5383136670726159,
 11.601666980030378,
 -14.734276129656037,
 24,
 1,
 '산청',
 0.43894873693813874,
 13.136114181751688,
 -11.429055923570862,
 25,
 1,
 '상주',
 -0.98326887591438,
 11.210314338266992,
 -12.455644527393455,
 26,
 1,
 '서귀포',
 7.508128253274109,
 17.303820260262572,
 -1.1614423240147107,
 27,
 1,
 '서산',
 -1.7286337618730212,
 10.634283977311453,
 -13.575812484815247,
 28,
 1,
 '서울',
 -2.003799207715337,
 9.682461393454915,
 -13.401689903968567,
 29,
 1,
 '속초',
 0.1093900730466886,
 10.832419385897868,
 -11.443725992451771,
 30,
 1,
 '수원',
 -2.1396011892667635,
 10.397653503412776,
 -14.277661176944342,
 31,
 1,
 '안동',
 -1.8549455926418856,
 11.119885589968394,
 -15.20971414584664,
 32,
 1,
 '양평',
 -3.5778014523481065,
 9.642858567119186,
 -17.504026250201267,
 33,
 1,
 '여수',
 2.925779922800321,
 12.888284820710538,
 -7.005025184527754,
 34,
 1,
 '영덕',
 1.1157852851280612,
 13.097806947747817,
 -10.551173799804266,
 35,
 1,
 '영월',
 -3.677891663940131,
 10.0200846808731,
 -18.17125179705168,
 36,
 1,
 '영주',
 -2.3667721706823426,
 9.985590066468761,
 -15.860676822256757,
 37,
 1,
 '영천',
 -0.510462559969546,
 12.576291101535565,
 -13.246878452205266,
 38,
 1,
 '완도',
 2.933186373440917,
 13.82696660791349,
 -5.72441202976921,
 39,
 1,
 '울릉도',
 1.8129964558313414,
 11.666226227607808,
 -6.759616924682089,
 40,
 1,
 '울산',
 2.4699476839178245,
 14.584661837086955,
 -8.534701175218737,
 41,
 1,
 '울진',
 1.4491927599044678,
 13.386299568574401,
 -10.06679235115849,
 42,
 1,
 '원주',
 -3.239810140976915,
 9.859255024246039,
 -16.651150833223504,
 43,
 1,
 '의성',
 -3.077334088945153,
 11.898940344777312,
 -17.943458335662392,
 44,
 1,
 '이천',
 -3.152002407907165,
 9.910000536230397,
 -17.200141814993838,
 45,
 1,
 '인제',
 -4.732987813557666,
 8.35455172365024,
 -19.29183718112104,
 46,
 1,
 '인천',
 -1.6066935010848153,
 9.748557308193075,
 -12.374668242357236,
 47,
 1,
 '임실',
 -2.5940686696762616,
 12.176470716330252,
 -17.040789874122318,
 48,
 1,
 '장수',
 -3.145234782276425,
 11.193960637846233,
 -17.855363973042934,
 49,
 1,
 '장흥',
 0.9998119171497618,
 14.126403730173559,
 -10.547939255934667,
 50,
 1,
 '전주',
 0.028331884597936362,
 12.928789828921184,
 -11.62336667260228,
 51,
 1,
 '정읍',
 -0.19314548734584697,
 12.841674555484017,
 -11.837898127525397,
 52,
 1,
 '제주',
 6.370047516111924,
 16.558254200853433,
 -0.8887364070125862,
 53,
 1,
 '제천',
 -4.850139802606061,
 8.889155122995584,
 -19.91132110502977,
 54,
 1,
 '진도',
 -0.6311963006433231,
 11.873982239785724,
 -9.35744943451188,
 55,
 1,
 '진주',
 0.2894226323008726,
 13.60207337230889,
 -12.207147858050968,
 56,
 1,
 '창원',
 2.717691615984804,
 13.893220774226432,
 -8.110576601897689,
 57,
 1,
 '천안',
 -2.4168688333759256,
 10.909947867673976,
 -16.215880616280465,
 58,
 1,
 '철원',
 -5.823867816532312,
 7.988827897370267,
 -20.869806523880616,
 59,
 1,
 '청주',
 -1.5284596771568921,
 10.839284842067359,
 -13.854644364646765,
 60,
 1,
 '춘천',
 -4.237062648503526,
 8.405408159635614,
 -18.059007128026416,
 61,
 1,
 '태백',
 -4.836076381800831,
 8.498757361929826,
 -17.888342418038043,
 62,
 1,
 '통영',
 3.2972343293569173,
 14.165645683759319,
 -7.15889008481573,
 63,
 1,
 '포항',
 2.3537051036730445,
 13.781381280456353,
 -8.754197588427289,
 64,
 1,
 '합천',
 -0.1432074518805744,
 13.430604093566483,
 -12.879925587994043,
 65,
 1,
 '해남',
 1.3978682840441836,
 14.132396584201734,
 -10.288431816066652,
 66,
 1,
 '홍천',
 -4.909267697424229,
 9.006103036759075,
 -19.79852026991756]

In [ ]:
df2.to_csv(f"./data/2081예측.csv", mode='w')